name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Add GitLab remote
        run: |
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/all1401249/mwanamama-shop.git
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      - name: Push to GitLab
        run: |
          git push gitlab main:main --force
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
